[package]
name = "reddit_fs"
version = "0.1.0"
authors = ["coolreader18 <33094578+coolreader18@users.noreply.github.com>"]

[dependencies]
fuse = "0.3"
rawr = "0.1"
libc = "0.2"
time = "0.1"
indexmap = "1.0"
ctrlc = "3.1"
e_num = { git = "https://github.com/coolreader18/e_num" }
